# Generated by Django 3.1.3 on 2020-11-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='value_bool',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
