# Generated by Django 3.1.4 on 2020-12-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0002_auto_20201122_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='name_cs',
            field=models.CharField(help_text='User-friendly attribute name', max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_de',
            field=models.CharField(help_text='User-friendly attribute name', max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_en',
            field=models.CharField(help_text='User-friendly attribute name', max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_es',
            field=models.CharField(help_text='User-friendly attribute name', max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_fr',
            field=models.CharField(help_text='User-friendly attribute name', max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_it',
            field=models.CharField(help_text='User-friendly attribute name', max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_nl',
            field=models.CharField(help_text='User-friendly attribute name', max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='enumvalue',
            name='value_cs',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True, verbose_name='Value'),
        ),
        migrations.AddField(
            model_name='enumvalue',
            name='value_de',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True, verbose_name='Value'),
        ),
        migrations.AddField(
            model_name='enumvalue',
            name='value_en',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True, verbose_name='Value'),
        ),
        migrations.AddField(
            model_name='enumvalue',
            name='value_es',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True, verbose_name='Value'),
        ),
        migrations.AddField(
            model_name='enumvalue',
            name='value_fr',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True, verbose_name='Value'),
        ),
        migrations.AddField(
            model_name='enumvalue',
            name='value_it',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True, verbose_name='Value'),
        ),
        migrations.AddField(
            model_name='enumvalue',
            name='value_nl',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True, verbose_name='Value'),
        ),
    ]
