# Generated by Django 3.1.4 on 2020-12-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0003_auto_20201221_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enumvalue',
            name='value_cs',
        ),
        migrations.RemoveField(
            model_name='enumvalue',
            name='value_de',
        ),
        migrations.RemoveField(
            model_name='enumvalue',
            name='value_en',
        ),
        migrations.RemoveField(
            model_name='enumvalue',
            name='value_es',
        ),
        migrations.RemoveField(
            model_name='enumvalue',
            name='value_fr',
        ),
        migrations.RemoveField(
            model_name='enumvalue',
            name='value_it',
        ),
        migrations.RemoveField(
            model_name='enumvalue',
            name='value_nl',
        ),
        migrations.AddField(
            model_name='enumvalue',
            name='value_display',
            field=models.CharField(db_index=True, default=None, max_length=50, verbose_name='Value Display'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enumvalue',
            name='value_display_cs',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='Value Display'),
        ),
        migrations.AddField(
            model_name='enumvalue',
            name='value_display_de',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='Value Display'),
        ),
        migrations.AddField(
            model_name='enumvalue',
            name='value_display_en',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='Value Display'),
        ),
        migrations.AddField(
            model_name='enumvalue',
            name='value_display_es',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='Value Display'),
        ),
        migrations.AddField(
            model_name='enumvalue',
            name='value_display_fr',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='Value Display'),
        ),
        migrations.AddField(
            model_name='enumvalue',
            name='value_display_it',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='Value Display'),
        ),
        migrations.AddField(
            model_name='enumvalue',
            name='value_display_nl',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='Value Display'),
        ),
    ]
