# Generated by Django 3.1.6 on 2021-02-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0004_auto_20201221_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='value_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
