# Generated by Django 3.2.3 on 2021-08-17 12:51

from django.db import migrations
import sortedm2m.fields
from sortedm2m.operations import AlterSortedManyToManyField


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0005_auto_20210217_1745'),
    ]

    operations = [
        AlterSortedManyToManyField(
            model_name='enumgroup',
            name='values',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='eav.EnumValue', verbose_name='Enum group'),
        ),
    ]
