# Generated by Django 5.0.6 on 2024-07-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0006_alter_enumgroup_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='name_pl',
            field=models.CharField(help_text='User-friendly attribute name', max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_th',
            field=models.CharField(help_text='User-friendly attribute name', max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='enumvalue',
            name='value_display_pl',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='Value Display'),
        ),
        migrations.AddField(
            model_name='enumvalue',
            name='value_display_th',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='Value Display'),
        ),
    ]
