# Generated by Django 3.2.6 on 2021-08-18 18:41

from django.db import migrations

def populate(apps, schema_editor):
    from eav.models import EnumGroup, EnumValue, Attribute

    seal_bag = EnumValue.objects.create(
        value='seal_bag',
        value_display='Seal Bag',
        value_display_fr='Minigrip'
    )
    plastic = EnumValue.objects.create(
        value='hard_plastic',
        value_display='Hard plastic',
        value_display_fr='Plastique dur'
    )
    glass = EnumValue.objects.create(
        value='transparent_glass',
        value_display='Transparent glass',
        value_display_fr='Verre transparent'
    )
    direct = EnumValue.objects.create(
        value='direct_contact',
        value_display='Direct contact',
        value_display_fr='contact direct'
    )
    unspecified = EnumValue.objects.create(
        value='unspecified',
        value_display='Unspecified',
        value_display_fr='Non spécifié'
    )

    measure_type = EnumGroup.objects.create(
        name='measure_type',
    )

    measure_type.values.add(seal_bag, plastic, glass, direct, unknown)

    Attribute.objects.create(
        slug='measure_type',
        name='Measure Type',
        name_fr='Type de mesure',
        datatype=Attribute.TYPE_ENUM,
        enum_group=measure_type
    )


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0006_alter_enumgroup_values'),
    ]

    operations = [
        migrations.RunPython(populate)
    ]
