# Generated by Django 3.2.6 on 2021-08-19 08:47

from django.db import migrations

def populate(apps, schema_editor):
    from eav.models import EnumGroup, EnumValue, Attribute
    from measures.models import Measure, Sample

    measures = Measure.eav_objects.filter(eav__through_packaging=True)
    seal_bag = EnumValue.objects.get(value='seal_bag')
    for measure in measures:
        measure.eav.measure_type = seal_bag
        measure.eav.save()


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0007_create_measure_type_enum'),
    ]

    operations = [
        migrations.RunPython(populate)
    ]
