# Generated by Django 5.1.2 on 2024-11-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0007_attribute_name_pl_attribute_name_th_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='name_ja',
            field=models.CharField(help_text='User-friendly attribute name', max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='enumvalue',
            name='value_display_ja',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='Value Display'),
        ),
    ]
