# Generated by Django 3.2.6 on 2021-08-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0005_auto_20210510_1305'),
        ('eav', '0008_migrate_through_packaging'),
    ]

    operations = [
    ]
